language: minimal

env:
  global:
    - IMAGE_NAME=saniaky/photo-market-tpl:${TRAVIS_BUILD_NUMBER:snapshot}

services:
  - docker

install: skip

script:
  - docker build -t ${IMAGE_NAME} .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master


# Job lifecycle:              https://docs.travis-ci.com/user/job-lifecycle/
# Minimal and Generic images  https://docs.travis-ci.com/user/languages/minimal-and-generic/
# Using Docker in Builds      https://docs.travis-ci.com/user/docker/