language: minimal

env:
  global:
    - IMAGE_NAME=saniaky/photo-market-tpl:${TRAVIS_BUILD_NUMBER:snapshot}

services:
  - docker

before_install:
  - docker build -t ${IMAGE_NAME} .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

# Using Docker in Builds
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/languages/minimal-and-generic/